theme = "catppuccin_latte_sam"

[editor]
bufferline = "always"
text-width = 120
idle-timeout = 200
completion-trigger-len = 1
color-modes = true
auto-format = false

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "block"

[editor.lsp]
display-inlay-hints = true
auto-signature-help = false

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-modification-indicator"]
center = []
right = ["diagnostics", "selections", "position", "position-percentage", "file-encoding"]

[editor.soft-wrap]
enable = true
wrap-at-text-width = true

[editor.smart-tab]
enable = false

[keys.normal]
C-h = [":toggle-option lsp.display-inlay-hints"]
C-s = [":toggle-option lsp.auto-signature-help"]

[keys.normal."]"]
g = ["save_selection", "goto_next_change"]

[keys.normal."["]
g = ["save_selection", "goto_prev_change"]
